### ISSUE TITLE
session management

### ISSUE THREAD

**Issue by ghost** [BlackCodec/jwm-session#1]
Hi,
I am also working on a similar project.  I have found a number of issues that need to be addressed (for Ubuntu specifically) and have a fairly full featured session that loads almost everything needed.
If you'd like to work together I'll post it and give you a link

**Comment by BlackCodec** [comment]
Sorry i don't use this wm. I have only posted a work on github for a friend that need that scripts.
I only tested it on Arch linux and it is running on a server but not more. In future i could try to improve them. If you like you can fork and submit bugs, i try to resolve but if are related to ubuntu i cant help you.
